[{"propertyTypes":
  [
    "Apartment Complex",
    "Assisted Living",    
    "Apartment Complex",
    "Assisted Living",
    "Commercial",
    "Fuel Center",
    "Golf Club",
    "Healthcare - Mixed Use per Bed",
    "Healthcare - Mixed Use per Room",
    "Hospital",
    "Hospital - per Bed",
    "Hotel",
    "Independent & Assisted Living",
    "Independent Living",
    "Industrial",
    "Mobile Home Community",
    "Multi-Family",
    "Nursing Home",
    "Office",
    "Office-Industrial",
    "Office-Warehouse",
    "Parking Lot",
    "Parking Structure",
    "Religious Facility",
    "Residential (SF)",
    "Residential-Retail-Office",
    "Resort-Hotel",
    "Restaurant",
    "Retail",
    "Retail - Office - Industrial",
    "Retail-Industrial",
    "Retail-Office",
    "School",
    "Self Storage Facility Per Unit",
    "Single-Family Residential",
    "Skilled Nursing",
    "Storage Facility",
    "Student Housing - Per Bed",
    "Student Housing - Per Room",
    "Warehouse",
    "Other..."
  ]
}]


